
set(PACKAGE_VERSION "")

if ("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "")
	set(PACKAGE_VERSION_COMPATIBLE TRUE)
	if ("${PACKAGE_FIND_VERSION_MINOR}" EQUAL )
		set(PACKAGE_VERSION_EXACT TRUE)
	endif()
else()
	set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()

